services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - cfinsights-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro,Z
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,Z
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  cfinsights-db:
