FROM golang:1.24 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN GOOS=linux CGO_ENABLED=0 go build -o ./fetcher ./cmd/fetcher/

FROM scratch

WORKDIR /app
COPY --from=builder /app/fetcher .

# Copy TLS certs.
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["./fetcher"]
