BEGIN;

CREATE TABLE IF NOT EXISTS contests (
	id SERIAL PRIMARY KEY,
	contest_id INT NOT NULL UNIQUE,
	name TEXT NOT NULL,
	start_time TIMESTAMP NOT NULL,
	duration INT NOT NULL,
	updated_at TIMESTAMP DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = NOW();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_contests_updated_at
BEFORE UPDATE ON contests
FOR EACH ROW
EXECUTE PROCEDURE set_updated_at();

COMMIT;
